[WIP]Chat-Spaceチャット画面の実装
nitro2046/chat-space pull request #5
Opened 2019-05-06 07:06 UTC by nitro2046

# WHAT
chat-spaceの開発にあたって、チャット画面indexのビューを用意すること

# WHY
メインとした画面のため、先に準備しておきたい

2019-05-12 11:56 UTC, kuroko918 commented on app/views/messages/_messages.html.haml
> +        %a{:href => "#"}
link_toの方が可読性が高いかと思いますので、そちらに変更お願いします！
他の部分も変更お願いします！

2019-05-12 11:57 UTC, kuroko918 commented on config/routes.rb
> +  resources :messages, only: [:index]
こちらは、rootに指定しておいてください！

2019-05-12 12:31 UTC, nitro2046 commented on app/views/messages/_messages.html.haml
> +        %a{:href => "#"}
修正しました

2019-05-12 12:31 UTC, nitro2046 commented on config/routes.rb
> +  resources :messages, only: [:index]
修正しました

2019-05-12 12:32 UTC, hiroki5123 commented
実際の画面のキャプチャをこちらに添付してください

2019-05-12 12:33 UTC, ghost requested changes

2019-05-12 12:33 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +  = render partial: 'messages'
これだと部分テンプレートに分けているメリットをあんまり感じられないので分ける必要もないかと思います

2019-05-12 12:59 UTC, nitro2046 commented on app/views/messages/index.html.haml
> +  = render partial: 'messages'
修正しました

2019-05-13 01:15 UTC, kuroko918 commented
いいかと思います！
LGTMです！

2019-05-13 04:31 UTC, merged